In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('datasetFinal.csv')

In [3]:
X = df.loc[:, df.columns != 'generated_power']
y = df.loc[:, df.columns == 'generated_power']
X.head()
y.head()
df.shape

(19401, 12)

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,random_state=7)

In [5]:
X_train.shape

(14550, 11)

In [6]:
X_test.shape

(4851, 11)

In [7]:
from sklearn.tree import DecisionTreeRegressor

In [8]:
reg = DecisionTreeRegressor(criterion ="friedman_mse", max_depth=10, 
                            min_samples_split=10, random_state=5)

In [9]:
reg.fit(X_train,y_train)

DecisionTreeRegressor(criterion='friedman_mse', max_depth=10,
                      min_samples_split=10, random_state=5)

In [10]:
y_pred = reg.predict(X_test)

In [11]:
y_pred

array([   0.  ,    0.  , 2231.25, ..., 1238.5 ,    0.  ,    0.  ])

In [12]:
from sklearn.metrics import mean_squared_error
mean_squared_error(y_test,y_pred)

182795.0197707059

In [13]:
np.sqrt(mean_squared_error(y_test,y_pred))

427.5453423564639

In [14]:
from sklearn.model_selection import cross_val_score
cross_val_score(reg,X_train,y_train, cv=10)

array([0.91253722, 0.91967064, 0.8821573 , 0.89869619, 0.91571112,
       0.907913  , 0.9079597 , 0.88095715, 0.90821368, 0.89718617])

In [15]:
A_test = [14,12,12,1014,200,4,43,96,4,12,33]
#X_test = [14,12,12,1014,200, 4,43, 96, 4,12, 33]
b = df.iloc[1001]
b= b.drop(columns='generated_power')
#b = b.reshape(-1, 1)
#dataf= pd.DataFrame({"X_test":"X_test"})
#dataf
pred = reg.predict([A_test])
pred


C:\Users\Francisco Oliveira\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:409: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(


array([250.47058824])

In [16]:
df1 = df.drop(columns='generated_power')

for i in range(10,100):
    predictionDataframe = reg.predict([df1.iloc[i]])
    print ('Real:', df.iloc[i]["generated_power"] ,'  mmh... I predict:',predictionDataframe)
    

Real: 384   mmh... I predict: [346.20155039]
Real: 388   mmh... I predict: [346.20155039]
Real: 537   mmh... I predict: [573.78651685]
Real: 514   mmh... I predict: [456.72131148]
Real: 379   mmh... I predict: [346.20155039]
Real: 281   mmh... I predict: [323.89208633]
Real: 0   mmh... I predict: [0.]
Real: 0   mmh... I predict: [0.]
Real: 0   mmh... I predict: [0.]
Real: 0   mmh... I predict: [0.]
Real: 0   mmh... I predict: [0.]
Real: 0   mmh... I predict: [0.]
Real: 0   mmh... I predict: [0.]
Real: 0   mmh... I predict: [0.]
Real: 0   mmh... I predict: [0.]
Real: 0   mmh... I predict: [0.]
Real: 242   mmh... I predict: [163.92]
Real: 239   mmh... I predict: [777.4]
Real: 883   mmh... I predict: [1856.8]
Real: 2019   mmh... I predict: [1661.36190476]
Real: 2509   mmh... I predict: [1885.04395604]
Real: 1492   mmh... I predict: [1036.95]
Real: 1322   mmh... I predict: [1376.45238095]
Real: 401   mmh... I predict: [456.72131148]
Real: 404   mmh... I predict: [456.72131148]
Real: 0   mm

C:\Users\Francisco Oliveira\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:409: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(
C:\Users\Francisco Oliveira\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:409: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(
C:\Users\Francisco Oliveira\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:409: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(
C:\Users\Francisco Oliveira\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:409: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(
C:\Users\Francisco Oliveira\AppData\Local\Programs\Python\Python311\Lib\site-pac